// Types for exerciseKinds.js (used from TypeScript by the Excel export).
export function defaultMode(name: string): "reps" | "time";
export function defaultSecs(name: string): number;
export function parseDuration(raw: unknown): number | null;
export function formatDuration(secs: unknown): string;
export function clock(secs: unknown): string;
export function durationInput(secs: unknown): string;
export function maskDuration(raw: unknown): string;
export function tidyDuration(raw: unknown): string;
export function supersetInfo(exercises: unknown[]): ({ letter: string; pos: number; size: number } | null)[];
export function normalizeSupersets<T>(exercises: T[]): T[];
export const SET_KINDS: Record<"warmup" | "drop" | "amrap", { short: string; label: string; hint: string }>;
export function setKind(s: unknown): "warmup" | "drop" | "amrap" | null;
export function rackRound(w: unknown, unit: string): number | null;
export function dropWeight(w: unknown, unit: string): number | null;
export function warmupWeight(w: unknown, unit: string): number | null;
export function setKindsSummary(list: unknown[]): string;
export const REST_OPTIONS: number[];
export function groupName(size: number): string;
export function restLabel(secs: unknown): string;
