-- ============================================================================
-- Theryn — Migration 007: Expanded exercise library
-- ============================================================================
-- Adds ~400 additional curated exercises across all muscle groups so the
-- public_exercises library covers the long tail of common gym movements
-- (variants by equipment, grip, stance, range; common typo aliases).
--
-- Idempotent: each row only inserts when no public_exercises row with the
-- same lower(name) already exists. Safe to re-run; safe across reseeds of
-- the original migration 001 seed block.
-- ============================================================================

INSERT INTO public_exercises (name, muscle_group, equipment, category, aliases)
SELECT v.name, v.muscle_group, v.equipment, v.category, v.aliases
FROM (VALUES

-- ── CHEST (additions) ──────────────────────────────────────────────────────
('Close Grip Bench Press (Chest)', 'chest', 'barbell',     'compound',  ARRAY['cgbp', 'narrow grip bench']),
('Wide Grip Bench Press',          'chest', 'barbell',     'compound',  ARRAY['wide grip bench']),
('Floor Press',                    'chest', 'barbell',     'compound',  ARRAY['barbell floor press']),
('Dumbbell Floor Press',           'chest', 'dumbbell',    'compound',  ARRAY['db floor press']),
('Larsen Press',                   'chest', 'barbell',     'compound',  ARRAY['larsen bench']),
('Spoto Press',                    'chest', 'barbell',     'compound',  ARRAY['paused bench']),
('Reverse Grip Bench Press',       'chest', 'barbell',     'compound',  ARRAY['underhand bench']),
('Incline Smith Press',            'chest', 'smith_machine','compound', ARRAY['smith incline press']),
('Decline Smith Press',            'chest', 'smith_machine','compound', ARRAY['smith decline press']),
('Single Arm Dumbbell Press',      'chest', 'dumbbell',    'compound',  ARRAY['one arm db press']),
('Single Arm Cable Press',         'chest', 'cable',       'compound',  ARRAY['one arm cable press']),
('Standing Cable Press',           'chest', 'cable',       'compound',  ARRAY['cable chest press standing']),
('Seated Machine Fly',             'chest', 'machine',     'isolation', ARRAY['pec deck fly machine', 'machine pec fly']),
('Cable Squeeze Press',            'chest', 'cable',       'isolation', ARRAY['cable squeeze']),
('Plyo Push-Up',                   'chest', 'bodyweight',  'compound',  ARRAY['clap pushup', 'plyometric pushup']),
('Wide Push-Up',                   'chest', 'bodyweight',  'compound',  ARRAY['wide grip pushup']),
('Archer Push-Up',                 'chest', 'bodyweight',  'compound',  ARRAY['archer pushup']),
('Spiderman Push-Up',              'chest', 'bodyweight',  'compound',  ARRAY['spiderman pushup']),
('Hindu Push-Up',                  'chest', 'bodyweight',  'compound',  ARRAY['hindu pushup', 'dive bomber']),
('Resistance Band Chest Press',    'chest', 'band',        'compound',  ARRAY['band chest press']),
('Resistance Band Fly',            'chest', 'band',        'isolation', ARRAY['band chest fly']),
('Single Arm Cable Fly',           'chest', 'cable',       'isolation', ARRAY['one arm cable fly']),
('Iso-Lateral Chest Press',        'chest', 'machine',     'compound',  ARRAY['hammer strength chest press', 'plate loaded chest press']),

-- ── BACK (additions) ───────────────────────────────────────────────────────
('Wide Grip Pull-Up',              'back', 'bodyweight',  'compound',  ARRAY['wide pullup', 'wide grip pullup']),
('Weighted Pull-Up',               'back', 'bodyweight',  'compound',  ARRAY['weighted pullup']),
('Assisted Pull-Up',               'back', 'machine',     'compound',  ARRAY['assisted pullup machine']),
('Wide Grip Lat Pulldown',         'back', 'cable',       'compound',  ARRAY['wide pulldown']),
('Behind The Neck Pulldown',       'back', 'cable',       'compound',  ARRAY['btn pulldown']),
('Single Arm Lat Pulldown',        'back', 'cable',       'compound',  ARRAY['one arm pulldown']),
('Kneeling Cable Pulldown',        'back', 'cable',       'compound',  ARRAY['kneeling pulldown']),
('Yates Row',                      'back', 'barbell',     'compound',  ARRAY['underhand bb row']),
('Barbell Row (Underhand)',        'back', 'barbell',     'compound',  ARRAY['supinated bb row']),
('Smith Machine Row',              'back', 'smith_machine','compound', ARRAY['smith row', 'smith bent row']),
('Dumbbell Pendlay Row',           'back', 'dumbbell',    'compound',  ARRAY['db pendlay']),
('Helms Row',                      'back', 'dumbbell',    'compound',  ARRAY['helms db row']),
('Trap Bar Deadlift',              'back', 'barbell',     'compound',  ARRAY['hex bar deadlift', 'trap bar dl']),
('Snatch Grip Deadlift',           'back', 'barbell',     'compound',  ARRAY['snatch dl']),
('Deficit Deadlift',               'back', 'barbell',     'compound',  ARRAY['deficit dl']),
('Romanian Deadlift (Back)',       'back', 'barbell',     'compound',  ARRAY['back rdl']),
('Banded Pull-Apart',              'back', 'band',        'isolation', ARRAY['band pull apart', 'pull apart']),
('Cable Pull-Apart',               'back', 'cable',       'isolation', ARRAY['cable pull apart']),
('Reverse Pec Deck',               'back', 'machine',     'isolation', ARRAY['rear delt pec deck']),
('Chest Supported T-Bar Row',      'back', 'machine',     'compound',  ARRAY['chest supported t bar']),
('Iso-Lateral Row',                'back', 'machine',     'compound',  ARRAY['hammer strength row', 'plate loaded row']),
('Iso-Lateral Pulldown',           'back', 'machine',     'compound',  ARRAY['hammer strength pulldown']),
('TRX Row',                        'back', 'bodyweight',  'compound',  ARRAY['trx body row']),
('Ring Row',                       'back', 'bodyweight',  'compound',  ARRAY['gymnastic ring row']),
('Bird Dog Row',                   'back', 'dumbbell',    'compound',  ARRAY['db bird dog row']),
('Renegade Row',                   'back', 'dumbbell',    'compound',  ARRAY['db renegade row']),
('Gorilla Row',                    'back', 'kettlebell',  'compound',  ARRAY['kb gorilla row']),
('Single Arm Lat Pullover',        'back', 'cable',       'isolation', ARRAY['cable single arm pullover']),
('Cable Pullover',                 'back', 'cable',       'isolation', ARRAY['rope pullover']),
('Hyperextension',                 'back', 'bodyweight',  'isolation', ARRAY['back extension', 'hyperextensions']),
('Reverse Hyperextension',         'back', 'machine',     'isolation', ARRAY['reverse hyper']),
('Banded Row',                     'back', 'band',        'compound',  ARRAY['band row']),

-- ── SHOULDERS (additions) ──────────────────────────────────────────────────
('Z Press',                        'shoulders', 'barbell',  'compound',  ARRAY['barbell z press']),
('Half Kneeling Press',            'shoulders', 'dumbbell', 'compound',  ARRAY['kneeling db press']),
('Standing Dumbbell Press',        'shoulders', 'dumbbell', 'compound',  ARRAY['standing db press']),
('Single Arm Dumbbell Press (Shoulder)', 'shoulders', 'dumbbell', 'compound', ARRAY['one arm db shoulder press']),
('Bottoms Up Press',               'shoulders', 'kettlebell','compound', ARRAY['kb bottoms up press']),
('Half Kneeling Cable Press',      'shoulders', 'cable',    'compound',  ARRAY['half kneeling cable shoulder press']),
('Machine Shoulder Press',         'shoulders', 'machine',  'compound',  ARRAY['shoulder press machine']),
('Iso-Lateral Shoulder Press',     'shoulders', 'machine',  'compound',  ARRAY['hammer strength shoulder press']),
('Cable Y Raise',                  'shoulders', 'cable',    'isolation', ARRAY['y raise']),
('Dumbbell Y Raise',               'shoulders', 'dumbbell', 'isolation', ARRAY['db y raise']),
('Cable Egyptian Lateral',         'shoulders', 'cable',    'isolation', ARRAY['egyptian lateral']),
('Leaning Lateral Raise',          'shoulders', 'dumbbell', 'isolation', ARRAY['leaning db lateral']),
('Seated Lateral Raise',           'shoulders', 'dumbbell', 'isolation', ARRAY['seated db lateral']),
('Lying Lateral Raise',            'shoulders', 'dumbbell', 'isolation', ARRAY['lying db lateral']),
('Cable Lateral (Single Arm)',     'shoulders', 'cable',    'isolation', ARRAY['single arm cable lateral']),
('Bent Over Lateral Raise',        'shoulders', 'dumbbell', 'isolation', ARRAY['bent over db lateral', 'rear delt lateral']),
('Face Pull (Rope)',               'shoulders', 'cable',    'isolation', ARRAY['rope face pull']),
('Cable Rear Delt Row',            'shoulders', 'cable',    'isolation', ARRAY['rear delt row']),
('Reverse Cable Crossover',        'shoulders', 'cable',    'isolation', ARRAY['rear delt crossover']),
('Banded Lateral Raise',           'shoulders', 'band',     'isolation', ARRAY['band lateral raise']),
('Banded Front Raise',             'shoulders', 'band',     'isolation', ARRAY['band front raise']),
('Banded Reverse Fly',             'shoulders', 'band',     'isolation', ARRAY['band reverse fly']),
('Pike Push-Up',                   'shoulders', 'bodyweight','compound', ARRAY['pike pushup']),
('Wall Walk',                      'shoulders', 'bodyweight','compound', ARRAY['wall walks']),
('Crucifix Hold',                  'shoulders', 'dumbbell', 'isolation', ARRAY['lateral hold']),
('Cable Upright Row',              'shoulders', 'cable',    'compound',  ARRAY['rope upright row']),
('Smith Machine Shrug',            'shoulders', 'smith_machine','isolation', ARRAY['smith shrug']),
('Trap Bar Shrug',                 'shoulders', 'barbell',  'isolation', ARRAY['hex bar shrug']),
('Cable Shrug',                    'shoulders', 'cable',    'isolation', ARRAY['rope shrug']),
('Behind The Back Shrug',          'shoulders', 'barbell',  'isolation', ARRAY['behind back shrug']),

-- ── QUADS (additions) ──────────────────────────────────────────────────────
('High Bar Squat',                 'quads', 'barbell',  'compound',  ARRAY['olympic squat', 'high bar back squat']),
('Low Bar Squat',                  'quads', 'barbell',  'compound',  ARRAY['low bar back squat']),
('Pause Squat',                    'quads', 'barbell',  'compound',  ARRAY['paused squat']),
('Tempo Squat',                    'quads', 'barbell',  'compound',  ARRAY['tempo back squat']),
('Heel Elevated Squat',            'quads', 'barbell',  'compound',  ARRAY['plate heel squat']),
('Heel Elevated Goblet Squat',     'quads', 'dumbbell', 'compound',  ARRAY['heel elevated db squat']),
('Cyclist Squat',                  'quads', 'barbell',  'compound',  ARRAY['quad squat']),
('Front Foot Elevated Split Squat','quads', 'dumbbell', 'compound',  ARRAY['ffss']),
('Walking Lunge',                  'quads', 'dumbbell', 'compound',  ARRAY['walking db lunge']),
('Stationary Lunge',               'quads', 'dumbbell', 'compound',  ARRAY['static lunge']),
('Lateral Lunge',                  'quads', 'dumbbell', 'compound',  ARRAY['side lunge']),
('Cossack Squat',                  'quads', 'dumbbell', 'compound',  ARRAY['cossack']),
('Goblet Cossack Squat',           'quads', 'dumbbell', 'compound',  ARRAY['goblet cossack']),
('Dumbbell Front Squat',           'quads', 'dumbbell', 'compound',  ARRAY['db front squat']),
('Kettlebell Goblet Squat',        'quads', 'kettlebell','compound', ARRAY['kb goblet squat']),
('Single Leg Press',               'quads', 'machine',  'compound',  ARRAY['one leg press']),
('Leg Press (Wide Stance)',        'quads', 'machine',  'compound',  ARRAY['wide stance leg press']),
('Single Leg Extension',           'quads', 'machine',  'isolation', ARRAY['one leg extension']),
('Banded Leg Extension',           'quads', 'band',     'isolation', ARRAY['band leg extension']),
('Step-Up to Knee',                'quads', 'dumbbell', 'compound',  ARRAY['step up knee drive']),
('Reverse Nordic',                 'quads', 'bodyweight','isolation', ARRAY['reverse nordic curl']),
('Spanish Squat',                  'quads', 'band',     'compound',  ARRAY['banded spanish squat']),
('Sissy Squat (Machine)',          'quads', 'machine',  'isolation', ARRAY['sissy squat machine']),
('Backward Sled Drag',             'quads', 'machine',  'compound',  ARRAY['reverse sled drag', 'backwards sled']),
('Forward Sled Drag',              'quads', 'machine',  'compound',  ARRAY['forward sled']),

-- ── HAMSTRINGS (additions) ─────────────────────────────────────────────────
('B Stance Romanian Deadlift',     'hamstrings', 'dumbbell', 'compound',  ARRAY['b stance rdl']),
('Single Leg RDL (Barbell)',       'hamstrings', 'barbell',  'compound',  ARRAY['single leg romanian deadlift barbell']),
('Stiff Leg DB Deadlift',          'hamstrings', 'dumbbell', 'compound',  ARRAY['db sldl']),
('Snatch Grip RDL',                'hamstrings', 'barbell',  'compound',  ARRAY['snatch grip romanian']),
('Deficit RDL',                    'hamstrings', 'barbell',  'compound',  ARRAY['deficit romanian']),
('Trap Bar RDL',                   'hamstrings', 'barbell',  'compound',  ARRAY['hex bar rdl']),
('Lying Leg Curl',                 'hamstrings', 'machine',  'isolation', ARRAY['prone leg curl']),
('Standing Leg Curl',              'hamstrings', 'machine',  'isolation', ARRAY['standing hamstring curl']),
('Banded Hamstring Curl',          'hamstrings', 'band',     'isolation', ARRAY['band leg curl']),
('Slider Hamstring Curl',          'hamstrings', 'bodyweight','isolation',ARRAY['slider leg curl']),
('Razor Curl',                     'hamstrings', 'bodyweight','isolation',ARRAY['razor hamstring curl']),
('Single Leg Glute Ham Raise',     'hamstrings', 'bodyweight','compound', ARRAY['single leg ghr']),
('Banded Good Morning',            'hamstrings', 'band',     'compound',  ARRAY['band good morning']),
('Cable Good Morning',             'hamstrings', 'cable',    'compound',  ARRAY['cable gm']),
('Reverse Hyper (Hamstrings)',     'hamstrings', 'machine',  'isolation', ARRAY['reverse hyper hamstrings']),

-- ── GLUTES (additions) ─────────────────────────────────────────────────────
('Single Leg Hip Thrust (Loaded)', 'glutes', 'dumbbell', 'compound',  ARRAY['single leg hip thrust loaded']),
('B Stance Hip Thrust',            'glutes', 'barbell',  'compound',  ARRAY['b stance thrust']),
('Smith Machine Hip Thrust',       'glutes', 'smith_machine','compound', ARRAY['smith hip thrust']),
('Banded Hip Thrust',              'glutes', 'band',     'compound',  ARRAY['band hip thrust']),
('Glute Bridge (Barbell)',         'glutes', 'barbell',  'compound',  ARRAY['barbell glute bridge']),
('Cable Hip Abduction',            'glutes', 'cable',    'isolation', ARRAY['cable abduction']),
('Standing Cable Kickback',        'glutes', 'cable',    'isolation', ARRAY['standing cable glute kickback']),
('Quadruped Hip Extension',        'glutes', 'bodyweight','isolation', ARRAY['donkey kick']),
('Banded Glute Bridge',            'glutes', 'band',     'compound',  ARRAY['band glute bridge']),
('Banded Lateral Walk',            'glutes', 'band',     'isolation', ARRAY['monster walk', 'crab walk']),
('Banded Clamshell',               'glutes', 'band',     'isolation', ARRAY['clamshell']),
('Step-Up (High Box)',             'glutes', 'dumbbell', 'compound',  ARRAY['high box step up']),
('Reverse Lunge to Knee Drive',    'glutes', 'dumbbell', 'compound',  ARRAY['reverse lunge knee drive']),
('Hip Hinge',                      'glutes', 'bodyweight','isolation', ARRAY['hip hinge drill']),
('Single Leg Romanian (Glutes)',   'glutes', 'dumbbell', 'compound',  ARRAY['sl rdl glutes']),

-- ── CALVES (additions) ─────────────────────────────────────────────────────
('Hack Squat Calf Raise',          'calves', 'machine',     'isolation', ARRAY['hack calf raise']),
('Smith Machine Standing Calf',    'calves', 'smith_machine','isolation',ARRAY['smith standing calf']),
('Dumbbell Calf Raise',            'calves', 'dumbbell',    'isolation', ARRAY['db calf raise']),
('Single Leg Dumbbell Calf Raise', 'calves', 'dumbbell',    'isolation', ARRAY['single leg db calf']),
('Seated Dumbbell Calf Raise',     'calves', 'dumbbell',    'isolation', ARRAY['seated db calf']),
('Banded Calf Raise',              'calves', 'band',        'isolation', ARRAY['band calf raise']),
('Tib Curl',                       'calves', 'machine',     'isolation', ARRAY['tibialis curl']),
('Banded Tib Raise',               'calves', 'band',        'isolation', ARRAY['band tib raise']),

-- ── BICEPS (additions) ─────────────────────────────────────────────────────
('Wide Grip Barbell Curl',         'biceps', 'barbell',  'isolation', ARRAY['wide curl']),
('Close Grip Barbell Curl',        'biceps', 'barbell',  'isolation', ARRAY['close grip bb curl']),
('Strict Curl',                    'biceps', 'barbell',  'isolation', ARRAY['strict barbell curl']),
('Cheat Curl',                     'biceps', 'barbell',  'isolation', ARRAY['cheat bb curl']),
('Standing Hammer Curl',           'biceps', 'dumbbell', 'isolation', ARRAY['standing db hammer']),
('Seated Dumbbell Curl',           'biceps', 'dumbbell', 'isolation', ARRAY['seated db curl']),
('Alternating Dumbbell Curl',      'biceps', 'dumbbell', 'isolation', ARRAY['alt db curl', 'alternating curl']),
('Twisting Dumbbell Curl',         'biceps', 'dumbbell', 'isolation', ARRAY['twist curl']),
('Rope Hammer Curl',               'biceps', 'cable',    'isolation', ARRAY['cable rope hammer']),
('Cable Single Arm Curl',          'biceps', 'cable',    'isolation', ARRAY['one arm cable curl']),
('High Cable Curl',                'biceps', 'cable',    'isolation', ARRAY['cable high curl']),
('Crossbody Cable Curl',           'biceps', 'cable',    'isolation', ARRAY['cross body cable curl']),
('Banded Curl',                    'biceps', 'band',     'isolation', ARRAY['band bicep curl']),
('Bench Preacher Curl',            'biceps', 'dumbbell', 'isolation', ARRAY['bench preacher']),
('Spider Curl (EZ Bar)',           'biceps', 'ez_bar',   'isolation', ARRAY['ez spider curl']),
('Incline Hammer Curl',            'biceps', 'dumbbell', 'isolation', ARRAY['incline db hammer']),
('Chin-Up (Biceps)',               'biceps', 'bodyweight','compound', ARRAY['chinup biceps']),
('Single Arm Preacher Machine',    'biceps', 'machine',  'isolation', ARRAY['preacher curl machine']),

-- ── TRICEPS (additions) ────────────────────────────────────────────────────
('Rope Tricep Pushdown',           'triceps', 'cable',      'isolation', ARRAY['rope pushdown', 'tricep rope pushdown']),
('Straight Bar Pushdown',          'triceps', 'cable',      'isolation', ARRAY['bar pushdown']),
('V Bar Pushdown',                 'triceps', 'cable',      'isolation', ARRAY['v-bar pushdown']),
('Reverse Grip Pushdown',          'triceps', 'cable',      'isolation', ARRAY['underhand pushdown']),
('Cable Skullcrusher',             'triceps', 'cable',      'isolation', ARRAY['cable skull crusher']),
('Lying Cable Tricep Extension',   'triceps', 'cable',      'isolation', ARRAY['lying cable extension']),
('Single Arm Overhead Extension',  'triceps', 'dumbbell',   'isolation', ARRAY['one arm db overhead']),
('Seated Overhead Tricep Extension','triceps', 'dumbbell',  'isolation', ARRAY['seated db overhead extension']),
('EZ Bar Overhead Extension',      'triceps', 'ez_bar',     'isolation', ARRAY['ez overhead extension']),
('Rope Overhead Tricep Extension', 'triceps', 'cable',      'isolation', ARRAY['rope overhead extension']),
('Smith Machine Close Grip Bench', 'triceps', 'smith_machine','compound',ARRAY['smith cgbp']),
('Floor Skull Crusher',            'triceps', 'dumbbell',   'isolation', ARRAY['db floor skull']),
('California Press',               'triceps', 'dumbbell',   'compound',  ARRAY['db california press']),
('Reverse Grip Bench (Triceps)',   'triceps', 'barbell',    'compound',  ARRAY['underhand bench triceps']),
('Banded Pushdown',                'triceps', 'band',       'isolation', ARRAY['band tricep pushdown']),
('Banded Overhead Extension',      'triceps', 'band',       'isolation', ARRAY['band overhead extension']),
('Pin Press',                      'triceps', 'barbell',    'compound',  ARRAY['barbell pin press']),
('Tricep Dip Machine',             'triceps', 'machine',    'compound',  ARRAY['machine tricep dip', 'dip machine']),
('Iso-Lateral Tricep Press',       'triceps', 'machine',    'isolation', ARRAY['hammer strength tricep press']),

-- ── FOREARMS (additions) ───────────────────────────────────────────────────
('Hammer Wrist Curl',              'forearms', 'dumbbell', 'isolation', ARRAY['hammer wrist']),
('Cable Wrist Curl',               'forearms', 'cable',    'isolation', ARRAY['cable forearm curl']),
('Cable Reverse Wrist Curl',       'forearms', 'cable',    'isolation', ARRAY['cable wrist extension']),
('Behind The Back Wrist Curl',     'forearms', 'barbell',  'isolation', ARRAY['behind back wrist curl']),
('Towel Pull-Up',                  'forearms', 'bodyweight','isolation', ARRAY['towel pullup']),
('Fat Grip Curl',                  'forearms', 'dumbbell', 'isolation', ARRAY['fat gripz curl']),
('Captains of Crush',              'forearms', 'bodyweight','isolation', ARRAY['grip trainer']),
('Pinch Grip Hold',                'forearms', 'barbell',  'isolation', ARRAY['pinch hold']),
('Wrist Roller',                   'forearms', 'bodyweight','isolation', ARRAY['wrist rope roller']),
('Suitcase Carry',                 'forearms', 'dumbbell', 'compound',  ARRAY['db suitcase carry']),

-- ── CORE (additions) ───────────────────────────────────────────────────────
('Weighted Plank',                 'core', 'bodyweight', 'isolation', ARRAY['plate plank']),
('RKC Plank',                      'core', 'bodyweight', 'isolation', ARRAY['hardstyle plank']),
('Side Plank with Reach',          'core', 'bodyweight', 'isolation', ARRAY['side plank reach']),
('Copenhagen Plank',               'core', 'bodyweight', 'isolation', ARRAY['copenhagen']),
('Hollow Hold',                    'core', 'bodyweight', 'isolation', ARRAY['hollow body hold']),
('Hollow Rock',                    'core', 'bodyweight', 'isolation', ARRAY['hollow body rock']),
('V-Up',                           'core', 'bodyweight', 'isolation', ARRAY['v ups']),
('Tuck-Up',                        'core', 'bodyweight', 'isolation', ARRAY['tuck ups']),
('Toes to Bar',                    'core', 'bodyweight', 'isolation', ARRAY['t2b']),
('Knees to Elbow',                 'core', 'bodyweight', 'isolation', ARRAY['k2e']),
('Captains Chair Leg Raise',       'core', 'machine',    'isolation', ARRAY['captains chair']),
('Roman Chair Sit-Up',             'core', 'bodyweight', 'isolation', ARRAY['roman chair situp']),
('Decline Bench Crunch',           'core', 'bodyweight', 'isolation', ARRAY['decline crunch']),
('Cable Woodchopper',              'core', 'cable',      'compound',  ARRAY['cable wood chopper']),
('Reverse Cable Woodchop',         'core', 'cable',      'compound',  ARRAY['low to high cable chop']),
('Stir The Pot',                   'core', 'bodyweight', 'isolation', ARRAY['stability ball stir the pot']),
('Standing Cable Crunch',          'core', 'cable',      'isolation', ARRAY['standing cable ab crunch']),
('Side Bend',                      'core', 'dumbbell',   'isolation', ARRAY['db side bend']),
('Cable Side Bend',                'core', 'cable',      'isolation', ARRAY['cable oblique bend']),
('Banded Anti Rotation',           'core', 'band',       'isolation', ARRAY['band pallof']),
('Suitcase March',                 'core', 'dumbbell',   'compound',  ARRAY['suitcase walk']),
('Farmer Carry (Core)',            'core', 'dumbbell',   'compound',  ARRAY['core farmer carry']),
('Overhead Carry',                 'core', 'dumbbell',   'compound',  ARRAY['db overhead carry']),
('Front Loaded Carry',             'core', 'dumbbell',   'compound',  ARRAY['front rack carry']),
('Sit-Up (Bodyweight)',            'core', 'bodyweight', 'isolation', ARRAY['situp', 'sit ups']),
('Banana Hold',                    'core', 'bodyweight', 'isolation', ARRAY['banana']),
('Reverse Crunch',                 'core', 'bodyweight', 'isolation', ARRAY['reverse ab crunch']),
('Ab Mat Crunch',                  'core', 'bodyweight', 'isolation', ARRAY['ab mat']),
('Cable Pallof Hold',              'core', 'cable',      'isolation', ARRAY['pallof hold']),
('Suitcase Deadlift',              'core', 'dumbbell',   'compound',  ARRAY['db suitcase deadlift']),

-- ── COMPOUND / FULL BODY (additions) ───────────────────────────────────────
('Hang Clean',                     'back',      'barbell',    'compound', ARRAY['hang clean']),
('Power Snatch',                   'shoulders', 'barbell',    'compound', ARRAY['barbell power snatch']),
('Hang Snatch',                    'shoulders', 'barbell',    'compound', ARRAY['hang snatch']),
('Push Jerk',                      'shoulders', 'barbell',    'compound', ARRAY['barbell push jerk']),
('Split Jerk',                     'shoulders', 'barbell',    'compound', ARRAY['barbell split jerk']),
('Clean Pull',                     'back',      'barbell',    'compound', ARRAY['clean pulls']),
('Snatch Pull',                    'back',      'barbell',    'compound', ARRAY['snatch pulls']),
('Kettlebell Clean',               'shoulders', 'kettlebell', 'compound', ARRAY['kb clean']),
('Kettlebell Snatch',              'shoulders', 'kettlebell', 'compound', ARRAY['kb snatch']),
('Kettlebell Press',               'shoulders', 'kettlebell', 'compound', ARRAY['kb press']),
('Kettlebell Goblet Press',        'shoulders', 'kettlebell', 'compound', ARRAY['kb goblet press']),
('Devil Press',                    'chest',     'dumbbell',   'compound', ARRAY['db devil press']),
('Bear Crawl',                     'core',      'bodyweight', 'compound', ARRAY['bear crawl']),
('Crab Walk',                      'core',      'bodyweight', 'compound', ARRAY['crab walks']),
('Wall Ball',                      'quads',     'bodyweight', 'compound', ARRAY['wall ball shot']),
('Medicine Ball Slam',             'core',      'bodyweight', 'compound', ARRAY['med ball slam']),
('Lateral Box Jump',               'quads',     'bodyweight', 'compound', ARRAY['side box jump']),
('Broad Jump',                     'quads',     'bodyweight', 'compound', ARRAY['standing broad jump']),
('Tuck Jump',                      'quads',     'bodyweight', 'compound', ARRAY['tuck jumps']),
('Clap Push-Up',                   'chest',     'bodyweight', 'compound', ARRAY['plyo clap pushup']),
('Burpee Pull-Up',                 'back',      'bodyweight', 'compound', ARRAY['burpee pullup']),
('Renegade Push-Up',               'chest',     'dumbbell',   'compound', ARRAY['renegade pushup']),

-- ── CARDIO (additions) ─────────────────────────────────────────────────────
('Incline Treadmill Walk',         'cardio', 'machine',    'cardio', ARRAY['incline walk treadmill']),
('Treadmill Sprint',               'cardio', 'machine',    'cardio', ARRAY['treadmill sprints']),
('Recumbent Bike',                 'cardio', 'machine',    'cardio', ARRAY['recumbent']),
('Spin Bike',                      'cardio', 'machine',    'cardio', ARRAY['spinning']),
('Concept2 Row',                   'cardio', 'machine',    'cardio', ARRAY['c2 row']),
('Air Squat (Cardio)',             'cardio', 'bodyweight', 'cardio', ARRAY['cardio air squat']),
('Jumping Jacks',                  'cardio', 'bodyweight', 'cardio', ARRAY['jumping jack']),
('High Knees',                     'cardio', 'bodyweight', 'cardio', ARRAY['high knee run']),
('Butt Kickers',                   'cardio', 'bodyweight', 'cardio', ARRAY['butt kicks']),
('Shadow Boxing',                  'cardio', 'bodyweight', 'cardio', ARRAY['shadowboxing']),
('Heavy Bag Boxing',               'cardio', 'bodyweight', 'cardio', ARRAY['heavy bag work']),
('Jump Rope (Double Under)',       'cardio', 'bodyweight', 'cardio', ARRAY['double under']),
('Jump Rope (Single)',             'cardio', 'bodyweight', 'cardio', ARRAY['single jump rope']),
('Stair Run',                      'cardio', 'bodyweight', 'cardio', ARRAY['stairs run', 'stair sprints']),
('Hill Sprint',                    'cardio', 'bodyweight', 'cardio', ARRAY['hill sprints']),
('Long Run',                       'cardio', 'bodyweight', 'cardio', ARRAY['long distance run']),
('Tempo Run',                      'cardio', 'bodyweight', 'cardio', ARRAY['tempo running']),
('Interval Run',                   'cardio', 'bodyweight', 'cardio', ARRAY['running intervals']),

-- ── STRETCH / MOBILITY (additions) ─────────────────────────────────────────
('90/90 Hip Stretch',              'glutes',     'bodyweight', 'stretch', ARRAY['90 90 hip']),
('Pancake Stretch',                'hamstrings', 'bodyweight', 'stretch', ARRAY['pancake']),
('Frog Stretch',                   'glutes',     'bodyweight', 'stretch', ARRAY['frog']),
('Lizard Stretch',                 'glutes',     'bodyweight', 'stretch', ARRAY['lizard pose']),
('Couch Stretch',                  'quads',      'bodyweight', 'stretch', ARRAY['couch hip stretch']),
('Cobra Stretch',                  'core',       'bodyweight', 'stretch', ARRAY['cobra pose']),
('Downward Dog',                   'back',       'bodyweight', 'stretch', ARRAY['down dog']),
('Upward Dog',                     'core',       'bodyweight', 'stretch', ARRAY['up dog']),
('Thread the Needle',              'back',       'bodyweight', 'stretch', ARRAY['thread needle']),
('Doorway Pec Stretch',            'chest',      'bodyweight', 'stretch', ARRAY['doorway chest stretch']),
('Banded Shoulder Stretch',        'shoulders',  'band',       'stretch', ARRAY['band shoulder stretch']),
('Banded Hip Distraction',         'glutes',     'band',       'stretch', ARRAY['band hip distraction']),
('Banded Ankle Mobilization',      'calves',     'band',       'stretch', ARRAY['band ankle mob']),
('Wall Calf Stretch',              'calves',     'bodyweight', 'stretch', ARRAY['calf wall stretch']),
('Standing Hamstring Stretch',     'hamstrings', 'bodyweight', 'stretch', ARRAY['hamstring stretch']),
('Seated Forward Fold',            'hamstrings', 'bodyweight', 'stretch', ARRAY['seated forward bend']),
('Butterfly Stretch',              'glutes',     'bodyweight', 'stretch', ARRAY['butterfly hip stretch']),
('Spinal Twist',                   'back',       'bodyweight', 'stretch', ARRAY['supine spinal twist']),
('Foam Roll (IT Band)',            'quads',      'bodyweight', 'stretch', ARRAY['it band roll']),
('Foam Roll (Calves)',             'calves',     'bodyweight', 'stretch', ARRAY['calf foam roll']),
('Foam Roll (Glutes)',             'glutes',     'bodyweight', 'stretch', ARRAY['glute foam roll']),
('Foam Roll (Lats)',               'back',       'bodyweight', 'stretch', ARRAY['lat foam roll']),
('Lacrosse Ball Glute',            'glutes',     'bodyweight', 'stretch', ARRAY['lacrosse glute trigger']),
('Lacrosse Ball Pec',              'chest',      'bodyweight', 'stretch', ARRAY['lacrosse pec trigger'])

) AS v(name, muscle_group, equipment, category, aliases)
WHERE NOT EXISTS (
  SELECT 1 FROM public_exercises pe
  WHERE lower(pe.name) = lower(v.name)
);
